team-telnyx/telnyx-meet

.github/workflows/ci.yml
package.json

chore(WEBRTC-1607): configure eslint and add linter/build checks on PR

---

hooks/room.ts
next.config.js

fix: run eslint on custom folders

---

components/JoinRoom.tsx

- Add missing prop types in JoinRoom file

chore: add missing types

---

components/RoomControls.tsx

This PR will disable Simulcast on published streams.

[WEBRTC-1683] fix: Disable Simulcast

---

components/ReportIssueModal.tsx

This PR fixes the incomplete state presented in the Report Issue modal.
| Before | After |
| ------ | ---- |
| <img width="1278" alt="before" src="https://user-images.githubusercontent.com/16728775/163530810-586c8b1a-9348-4ade-bda9-c68389cdaba9.png"> | <img width="1280" alt="after" src="https://user-images.githubusercontent.com/16728775/163530833-7d265a72-cff0-494a-ae1e-f90f9840fe3c.png"> |

[WEBRTC-1680] Fix Incomplete State on Report Issue

---

components/Room.tsx
components/RoomControls.tsx
contexts/TelnyxMeetContext.ts
pages/rooms/[roomId].tsx
pages/rooms/index.tsx

This PR makes it possible to enable experimental features using URL query flags. It also gives more flexibility to include or exclude experimental features.

[WEBRTC-1682] Move Experimental Features behind a URL Flag

---

components/Feed.tsx
package.json
yarn.lock

-  remove video bitrate component as it is buggy

fix(WEBRTC-1708): remove video bitrate component as it is buggy

---

package.json
yarn.lock

- upgrade telnyx/video dependency
This new version fixes the network metrics report issue when it has PSTN participant.

chore(WEBRTC-1727): upgrade telnyx/video dependency

---

components/Feed.tsx
components/MediaPreview/MediaControlBar.tsx
utils/virtualBackground.ts

- add a blur effect in the background of the video
- refactor createVirtualBackgroumStream to enable blur and background images

feat(WEBRTC-1787): add blur effect in the background of video

---

package.json
yarn.lock

This PR upgrades telnyx-video SDK to its latest version.

chore: upgrade telnyx video sdk

---

pages/api/client_token.ts
pages/api/dial_out.ts
pages/api/refresh_client_token.ts
pages/api/rooms/[roomId].ts
pages/api/rooms/index.ts

When a API request response status is equal or above `500`, telnyx-meet does not return the server message.
This PR will return any server message for request response that are not `response.ok`.

[WEBRTC-1712] Send JSON Response on All API Response Status

---

components/Room.tsx
hooks/room.ts
package.json
yarn.lock

- Enable metrics for all new participants and disable them for the ones that leave the room
- Enable metrics automatically if network_metrics=true is set in the query parameters

refact(WEBRTC-1909): Enable metrics for all new participants and disable for the ones that leave the room

---

components/Feed.tsx
components/NetworkMetricsMonitor.tsx
components/Room.tsx
components/RoomControls.tsx
components/VideoBitrate.tsx
components/WebRTCStats.tsx

Component `Feed` currently has three child components that directly, or indirectly, use methods that are called repeatedly. Two of these methods are set in the `Feed` component, causing it to rerender unnecessarily.
This PR will move these timed called methods into their respective child component.

[WEBRTC-1915] Self Contain Components with Repeatedly Called Methods

---

components/Feed.tsx
components/GridLayout.tsx
components/MediaPreview/MediaControlBar.tsx
components/RoomControls.tsx
components/VideoTrack.tsx
package.json
utils/virtualBackground.ts
yarn.lock

- Fixing types in telnyx-meet and video-processors
- Upgrade processor lib and fix types

chore(WEBRTC-1981): Fixing types in telnyx-meet and video-processors

---

pages/api/client_token.ts
pages/api/dial_out.ts
pages/api/refresh_client_token.ts
pages/api/rooms/[roomId].ts
pages/api/rooms/index.ts
utils/helpers.ts

- When Telnyx API was returning errors to nextjs backend was not sending the correct data for the browser.

hotfix(WEBRTC-1980): response data from nextJS API when get error

---

components/MediaPreview/MediaControlBar.tsx
components/MediaPreview/index.tsx
components/MenuList.tsx
components/Room.tsx
components/RoomControls.tsx
components/VideoTrack.tsx
utils/virtualBackground.ts

- When using the virtual background feature and disabling the webcam it seems to be with the light green enabled indicating that it is still being in use even though the video screen is disabled.

fix(WEBRTC-1984): Using virtual background was not turn of the webcam when stopping to use it.

---

components/Chat.tsx

- add automatic scroll bottom when receiving many messages in chat box

feat(WEBRTC-2017): add automatic scroll bottom when receiving many messages in chat box

---

components/RoomControls/RoomControls.tsx
components/RoomControls/styles.ts
package.json
yarn.lock

- upgrade video SDK
- show leave button in desktop view

feat(WEBRTC-2034): upgrade video SDK

---

components/RoomControls/RoomControls.tsx

We are removing the Mixed Audio Button code that is duplicated.

fix: Removing the Mixed Audio Button code that is duplicated.

---

package.json
yarn.lock

chore(WEBRTC-2059): upgrade video sdk

---

components/MediaPreview/index.tsx
package.json
pages/rooms/index.tsx
yarn.lock

- add diagnostics library and add a button in telnyx meet to call video diagnostics function
- add a feature flag to toggle the button diagnostics visibility you need to add this query parameters `?diagnostics=true`

feat(WEBRTC-2067): add diagnostics library and add a button in telnyx meet to call video diagnostics function

---

hooks/room.ts
package.json
yarn.lock

- add reason message in the disconnected event and show pop with it.

feat(WEBRTC-2111): add reason message in the disconnected event and show pop with it.

---

hooks/room.ts

Shows speaking activity for PSTN participants

fix(WEBRTC-2116): show audio activity in the UI for PSTN participants

---

hooks/room.ts
package.json
yarn.lock

- feat(WEBRTC-2112): add max_timeout_reached disconnection reason

feat(WEBRTC-2112): add max_timeout_reached disconnection reason

---

hooks/room.ts
package.json
yarn.lock

- add try catch block in connectAndJoinRoom function to handle the errors that comes from the video SDK

feat(WEBRTC-2117): add try catch block in connectAndJoinRoom function

---

.gitignore
components/JoinRoom.tsx
components/Room.tsx
hooks/room.ts
pages/rooms/index.tsx

- add auto-reconnect when receiving a network error
- add a feature flag `?auto_reconnect=true`
- add a limit to try to reconnect we set a max of 3 chances to reconnect.
1 - run `yarn` and `yarn dev`
2 - access the URL with `?auto_reconnect=true` in it.
3 - Try to connect and in the middle of the connection disable your WIFI for 30 seconds and turn it on.
4 - It should show a notification in the UI and start to reconnect automatically

feat(WEBRTC-2122): add auto reconnect when receive a network error

---

yarn.lock

chore(ENGDESK-19633): upgrade video sdk
